{ config, lib, pkgs, ... }:

let
  cfg = config.modules.desktop.hyprland;
in {
  options.modules.desktop.hyprland = {
    enable = lib.mkEnableOption "Starter Hyprland Wayland compositor setup";
  };

  config = lib.mkIf cfg.enable {
    # 1. Enable Hyprland
    programs.hyprland = {
      enable = true;
      xwayland.enable = true;
    };

    # 2. XDG Desktop Portal (Crucial for screen sharing and Flatpaks)
    xdg.portal = {
      enable = true;
      extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
    };

    # 3. Environment Variables
    environment.sessionVariables = {
      # Hints Electron apps to use Wayland natively
      NIXOS_OZONE_WL = "1"; 
    };

    # 4. Basic System Packages
    # These are the bare minimums to make the default Hyprland config usable
    environment.systemPackages = with pkgs; [
      kitty           # The default terminal in Hyprland's autogenerated config
      rofi            # A basic Wayland app launcher
      waybar          # A standard Wayland status bar
      dunst           # Notification daemon
      wl-clipboard    # Command-line copy/paste utilities for Wayland
    ];

    # 5. Display Manager
    # SDDM is currently the most robust display manager for Wayland sessions
    services.displayManager.sddm = {
      enable = true;
      wayland.enable = true;
    };

    # Input device configuration
    services.libinput.enable = true;

  };
}